### ISSUE TITLE
Please update regex to support dot within params name

### ISSUE THREAD

**Issue by baggito** [parvez3019/go-swagger3#28]
We have query params formatted like this: 

// @Param  filter.id
// @Param  filter.locationId

and it cuts prefix part and only accepts everything after dot:

**Swagger:**
<img width="756" alt="Screenshot 2023-09-18 at 10 44 15 AM" src="https://github.com/parvez3019/go-swagger3/assets/17008739/524e1d04-e083-454f-9201-9eda594a243a">

**Openapi.json:**
...
```
paths:
  /assortment/planogram:
    get:
      description: ' Returns planogram based on query params.'
      parameters:
      - description: Use as filter.id! Planogram dbKey [comma separated list]
        in: query
        name: id
        required: true
        schema:
          description: Use as filter.id! Planogram dbKey [comma separated list]
          format: string
          type: string
      - description: Use as filter.locationId! Location ID
        in: query
        name: locationId
        required: true
        schema:
          description: Use as filter.locationId! Location ID
          format: string
          type: string
```

Is there any way to use params with dot?

Thanks.

**Potential fix that works:**
Within `parser/operations/param.go`, update regular expression to this one to support dot as well: 
```
re := regexp.MustCompile(`([-.\w]+)[\s]+([\w]+)[\s]+([\w./\[\]]+)[\s]+([\w]+)[\s]+"([^"]+)"`)
```
