### ISSUE TITLE
If you have an alias the schema component created for the alias is wrong

### ISSUE THREAD

**Issue by Keithwachira** [parvez3019/go-swagger3#43]
If you have an alias like below:

```
type APIResponse = ApiError

type ApiError struct {
	Status  string
	Message string
	Meta    interface{}
	ID      string `json:",omitempty"`
}
```

The schema created is wrong. It produces

```
components:
  schemas:
    APIResponse:
      type: ApiError
```
